language: cpp
before_script:
  - wget https://github.com/TITAN2D/titan2d/releases/download/v4.0.0/titan2d_dep-v4.0.0.tar.gz -O /tmp/titan2d_depv4.0.0.tar.gz
  - tar xvzf /tmp/titan2d_depv4.0.0.tar.gz
script:
  - autoreconf --install
  - ./configure --prefix=/tmp/titan --enable-openmp --with-titan2d-dep=/tmp/titan2d_dep-v4.0.0 --enable-portable
  - make
  - make install
before_deploy:
  - tar -zcf titan-bin.tar.gz /tmp/titan
deploy:
  provider: releases
  api_key:
    secure: WiHneqTzGFKcYSchE2YM/vum+u2UKHwxEpY51VmlxrwOm7hrKgSFnoYAaq/L+CJa7cL9HsbhEQrvznhYCl6xBI3Ic88pZZggy5qtv5axgLNtjGnH3LVqwqT0MQXf7V+wqBB01J4aSvW9EGtHaqOVuvT8MRPKd9Pa4rzBxlnsWn1eEJskgGOlmR2p9y+A29vKef5L7QmwGGB8PgdcEuFeF1dPzyrRjnpeNPtf3zWWAPjUfzOvmlXZfVCg7IbdDZoyfzv3qs9LcB7WPllvbf4yeWDKSQX5O6OqBLlTW+RmksqNwoPWaFD+3qx9dSHXX9ek3SkTKNdHICOw4IYjM6h2u2/MkMAUELs1TwcJN4szHfFIdu2AzBcDAw8qrjL51CMzeFoVzHvO+wB4acpbWkf7/iuQSelIfARUAdsR31MaNcCBUhUFsi0mo/pH+J/o3otpL2rNVnF4ZuOR9ttwyQI6aw8cEyqDGV46VCnLB54QFNeLgzyaB+0toSUDDHu5qCgdF66YYGjcmTl2gNMifYKl65Fv48CmiOwVnisua8Y3if4KnNNF0+4vsRnF7MFHodZivegzKeWtY7/6HFD+bfi0dFPWa+sXyLzJB/+5oGw8I0GpFEYnJViAWp2ywuho6vBPvAWGgtvHPHj2yreD8H4j6n6+rgleBXl20kWnr/IWlDI=
  file: titan-bin.tar.gz
  skip_cleanup: true
  on:
    tags: true
